"""
This one assumes we start from arch
"""

from shir import types, layout, config, bit_utils
from shir.codegen.project import SHIRProject
import torch
from torch.fx import GraphModule, Node
from pathlib import Path
import shir.codegen.arch_lowering

def fetch_lowering(key):
  return shir.codegen.arch_lowering.fetch_lowering(key)

def has_many_uses(node: Node) -> bool:
  user_count = len(node.users)
  if user_count > 1:
    return True

  used = False
  for user in node.users:
    # each user may have multiple occurrences / uses of a single node
    for n in user.all_input_nodes:
      if n != node:
        continue
      if used:
        return True
      used = True

  return False

class Project(SHIRProject):
  def __init__(self, clname: str, output_dir: Path):
    super(Project, self).__init__(clname, output_dir)

  def emit_source(self, gm, host_mapping):
    with (self.output_dir / f"{self.clname}.scala").open("w", encoding="utf-8") as f:
      print("""// This file is autogenerated

import core._
import core.compile.CompilerPhase
import core.rewrite.RewriteStep
import java.nio.file.Paths

object """, self.clname, """ extends support.GeneratedModel {

  override val name: String = """, "\"", self.clname, "\"", """

  def main(args: Array[String]): Unit = support.Util.drive(this, args)

  override def extraRewrites(): Seq[(CompilerPhase, RewriteStep)] = Seq()
""", sep='', file=f)

      self._emit_method_load_data(f, gm, host_mapping)
      print(file=f)

      self._emit_method_generate_ir(f, gm, host_mapping)
      print("}", file=f)


  def _emit_method_load_data(self, f, gm, host_mapping):
    print("  override def loadData(folder: String): Predef.Map[String, Seq[Seq[Int]]] = Predef.Map(", file=f)

    output_node = None
    for n in gm.graph.nodes:
      if n.op == "output":
        assert output_node is None, f"Multi-output node not supported"
        assert isinstance(n.args[0], Node), "Multi-valued output node not supported"
        output_node = n.args[0].meta.get("val")
        continue

      # it is either a placeholder or a intermediate node.
      # in either case, consult the host_mapping table.
      if n in host_mapping:
        host_id = host_mapping[n][0]

        # if it is an input, read the values from csv files.
        # otherwise, just create a bunch of 0's (like in the result case)
        if n.op == "placeholder":
          print(
            "    \"", host_id, "\" -> support.Util.readIntCSV(Paths.get(folder, \"",
            host_id, ".csv\").toFile()),",
            sep="", file=f
          )
        else:
          (outer, inner) = layout.reshape_size_to_matrix(n.meta.get("val").shape)
          print(
            "    \"", host_id, "\" -> new support.UniformSeq(new support.UniformSeq(0, ",
            inner, "), ", outer, "),",
            sep="", file=f
          )

    # for the result, we still need to give it some dummy value for simulation
    # to determine the RAM size.
    (outer, inner) = layout.reshape_size_to_matrix(output_node.shape)
    print(
      "    \"result\" -> new support.UniformSeq(new support.UniformSeq(0, ",
      inner, "), ", outer, ")",
      sep="", file=f
    )

    print("  )", file=f)

  def _emit_method_generate_ir(self, f, gm, host_mapping):
    print("  override def generateIR(): Expr = {", file=f)

    for n in gm.graph.nodes:
      # XXX: if needed, copy from algo.py
      assert not has_many_uses(n), "multi user not handled yet"

      if n.op == "placeholder":
        host_id, real_typ = host_mapping[n]
        ndim = n.meta.get("val").ndim
        shape = [*n.meta.get("val").shape]

        transpose, (h, w) = layout.pack_host_shape(shape)
        shape = [shape[x] for x in transpose]

        assert list(transpose) == list(range(0, ndim)), "TODO: transpose"

        node = f"arch.mem.Input(\"{host_id}\", {w}, {h}, {real_typ.name()})"
        print(
          "    val ", n.name, " = core.TypeChecker.check(", node, ")",
          sep="", file=f
        )

      elif n.op == "output":
        # sometimes, due to unfortunate graph slicing, we may end up with
        # multiple outputs, which we cannot handle
        [retv] = n.args
        assert isinstance(retv, Node), "Only single node output is allowed"

        annot_typ = types.get_element_type(retv)
        dims = retv.meta.get("val").ndim
        v = retv.name

        if dims < 1:
          v = f"arch.Repeat({v}, 1)"
        if dims < 2:
          v = f"arch.Repeat({v}, 1)"
        if dims > 2:
          assert False, "TODO: flattening logic"

        print(
          "    core.TypeChecker.check(arch.MapOrderedStream(2,",
          " arch.ResizeInteger.asFunction(types = Seq(", annot_typ.bits, ")),",
          " ", v, "))",
          sep="", file=f
        )

      elif n.op == "call_function":
        obj = fetch_lowering(n.target)
        expr = obj.lower(*n.args, **n.kwargs)
        if n in host_mapping:
          # add buffering if necessary.
          expr = f"mem.BufferStreamInHostRam({expr}, core.TextType(\"{host_mapping[n][0]}\"))"

        print(
          "    val ", n.name, " = core.TypeChecker.check(", expr, ")",
          sep="", file=f
        )

      else:
        assert False, "Unhandled fx node type when emitting"

    print("  }", file=f)

